### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by maxxcrawford** [tulsaux/uxok-planning#1]
Website should have support multiple phases: 
- Event announcement
- Call for speaker proposals  
- Tickets
- Day of
- Post event / recap 

Content should include: 
- Branding
- About Conference
- Speakers / Sponsor Sign-up
- Techlahoma / Code of Conduct Policy
- Sponsors 
- Day-of Schedule
- Location/Venue
- After-party
- Ticket options/link
- Get involved / Volunteer 
   - Reviewer for CFPs 
- Team/Volunteers 

Site features: 
- Namespaced for multi-year support

**Comment by maxxcrawford** [comment]
https://github.com/tulsaux/uxok-website

**Comment by nexocentric** [comment]
https://websitename/2017

for previous years, current year should be

https:/websitename/ should be the current
