### ISSUE TITLE
Select Tulsa 2020 venue

### ISSUE THREAD

**Issue by maxxcrawford** [tulsaux/uxok-planning#2]
**Criteria:**
- 200-250 person capacity
- Flexible catering options 
  - Vegan/GF Options
- Space for
  - Catering
  - Speaker Green Room
  - Sponsor Booth Fair 
  - Co-working/break area 
  - Parking

Options: 
- Philbrook Museum: Patti Johnson Wilson Hall
- Living Arts Center: Myers Gallery
- Tulsa Public Library: Pocahontas Greadington Learning & Creativity Center
- Circle Cinema: Historic Art House Theatre

**Comment by maxxcrawford** [comment]
Additional notes: 

- Need 3-5 locations to target for a Friday conference + after party (either same location or nearby)
- Discuss/Negotiate rental pricing (we’re non-profit-- any price breaks for that?)
- Need to provide 2-3 ideal dates to see if their schedules are open
- Discuss A/V, parking, logistics etc.
- Discuss food (how much, rules-- can we cater out?, etc)
- Marketing (ex: Philbrook might help w/ marketing our event on their own channels) This would be cool for any event location host.
- Any special perks? (ex:  Philbrook might be able to give attendees free or discounted museum admission pass..)
- What can we provide to the location in addition to payment. (ex: marketing of our event + the location on social media + otherwise, etc)

**Comment by VictoriaSchwaner** [comment]
Notes on location options in Tulsa:

1. [Philbrook Museum](https://philbrook.org/visit/host-an-event/private-events/): Patti Johnson Wilson Hall
- cool space
- not in the city
- good parking
- $$$ food, negotiate?
- free admission for conference guests?
- Take advantage of our experienced service staff and the on-site catering from Kitchen 27. We’ll help manage the details, from valet service and floral arrangements to equipment rentals and entertainment.
- Pricing, there are multiple levels, need investigation> Auditorium, $1000
- A/V quote?

2. [Living Arts Center: Myers Gallery](http://www.livingarts.org/about/rentals/)
- With 6,000 sq. ft in the Myers Gallery and 1,600 sq. ft in the West End Gallery, Living Arts of Tulsa can accommodate a range of events. 
- Official capacity at 280, staging and sound, a prep kitchen and bar, and bistro tables.
- Myers Gallery Rental Rate
Standard Rate – $2500 (weekend) $2000 (weekday)
Non-Profit Rate – $1500 (weekend) $1000 (weekday)
West End Gallery -$1000 (Standard) $750 (nonprofit)

3. [Tulsa Public Library: Pocahontas Greadington Learning & Creativity Center](https://www.tulsalibrary.org/using-the-library/venues-central-library)
- Creativity Center> Max Capacity: 300; Seated dinner: 225
- limits activities
- not that cool?


4.[ Circle Cinema: Historic Art House Theatre](http://www.circlecinema.org/facility-rental/)
- Auditorium 1, Capacity: 222 and 7 ADA spaces
- Regular Rate: Starting at $1,300
- Nonprofit Rate: Starting at $1,000

5. [AHHA](https://ahhatulsa.org/facility-rental/)
- cool arts space
- Capacity> 150-175 at tables, depending on space being used.
    > 200-250 setup as a mix of cocktail and sit-down styles, depending on space being used.
- Wednesday through Sunday:  $5,500
- Price includes 3 floors of the building for 8 hours total.
- A/V quoted according to event needs
- 20% discount to nonprofits who can provide a 501 C-3 determination
- 25% discount to Council Members*
- cool rooftop - after-party location?
- downtown/walkable 
- next door to Philbrook Downtown... right next to Marriott... 
- another great spot for the afterparty if not on-site would be [Welltown Brewing](https://www.welltownbrewing.com/weltown-brewing). They have a great upstairs room and rooftop...

6. [MotherRoad Market](https://www.motherroadmarket.com/eventform)
- seems fairly small and wouldn't support 200-250 attendees.. TBD

**Comment by maxxcrawford** [comment]
Trello Board created for progress tracking: https://trello.com/b/xew1nvcR/uxok-venue-tracking

Note that as of this comment, all 5 venues (Mother Road was not included) have been contacted.

**Comment by maxxcrawford** [comment]
Summary of all the venues, including RFP responses: 

https://docs.google.com/document/d/1aRRVDAsP_L9uF8lTIZaOO7BHHo994veuJMFRX0qYv2s/edit?usp=sharing
